Only re-define default rake task when RSpec available.
On e.g. production systems it isn't:

       rake aborted!
       NameError: uninitialized constant RSpec
       /home/hammock/rails/tmp/build-140802803216559/Rakefile:12:in `block in <top (required)>'
       /home/hammock/rails/tmp/build-140802803216559/Rakefile:10:in `<top (required)>'